[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers=
    advertisement: Маркировка для тестов, связанных с объявлениями.
    regression: Маркировка для регрессионных тестов.
    bug: Тест связан с известным багом.
